

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import Project.*;
import javax.swing.JOptionPane;


/**
 *
 * @author Acer
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuDonor = new javax.swing.JMenu();
        menuItemAddDonor = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuItemUpdateDonor = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuItemDonorDetails = new javax.swing.JMenuItem();
        menuSearch = new javax.swing.JMenu();
        menuItemLocation = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuItemBloodGrp = new javax.swing.JMenuItem();
        menuStock = new javax.swing.JMenu();
        menuItemIncrease = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menuItemDecrease = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        menuItemStockDetails = new javax.swing.JMenuItem();
        menuDelete = new javax.swing.JMenu();
        menuItemDeleteDonor = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenu();
        menuItemLogout = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        menuItemExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/homepagewow_4.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -410, 1310, 1380));

        menuDonor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Donor.png"))); // NOI18N
        menuDonor.setText("Donor");
        menuDonor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        menuItemAddDonor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemAddDonor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuItemAddDonor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add new.png"))); // NOI18N
        menuItemAddDonor.setText("Add New Donor");
        menuItemAddDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAddDonorActionPerformed(evt);
            }
        });
        menuItemAddDonor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                menuItemAddDonorKeyReleased(evt);
            }
        });
        menuDonor.add(menuItemAddDonor);
        menuDonor.add(jSeparator1);

        menuItemUpdateDonor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemUpdateDonor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuItemUpdateDonor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Update details.png"))); // NOI18N
        menuItemUpdateDonor.setText("Update Details");
        menuItemUpdateDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemUpdateDonorActionPerformed(evt);
            }
        });
        menuDonor.add(menuItemUpdateDonor);
        menuDonor.add(jSeparator2);

        menuItemDonorDetails.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemDonorDetails.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuItemDonorDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Details.png"))); // NOI18N
        menuItemDonorDetails.setText("All Donor Details");
        menuItemDonorDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDonorDetailsActionPerformed(evt);
            }
        });
        menuDonor.add(menuItemDonorDetails);

        jMenuBar1.add(menuDonor);

        menuSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search user.png"))); // NOI18N
        menuSearch.setText("Search Blood Donor");
        menuSearch.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSearchActionPerformed(evt);
            }
        });

        menuItemLocation.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuItemLocation.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuItemLocation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Location.png"))); // NOI18N
        menuItemLocation.setText("Location");
        menuItemLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLocationActionPerformed(evt);
            }
        });
        menuSearch.add(menuItemLocation);
        menuSearch.add(jSeparator3);

        menuItemBloodGrp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuItemBloodGrp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuItemBloodGrp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Blood group.png"))); // NOI18N
        menuItemBloodGrp.setText("Blood Group");
        menuItemBloodGrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBloodGrpActionPerformed(evt);
            }
        });
        menuSearch.add(menuItemBloodGrp);

        jMenuBar1.add(menuSearch);

        menuStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/stock.png"))); // NOI18N
        menuStock.setText("Stock");
        menuStock.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        menuItemIncrease.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        menuItemIncrease.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuItemIncrease.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Inc.png"))); // NOI18N
        menuItemIncrease.setText("Increase");
        menuItemIncrease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemIncreaseActionPerformed(evt);
            }
        });
        menuStock.add(menuItemIncrease);
        menuStock.add(jSeparator4);

        menuItemDecrease.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        menuItemDecrease.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuItemDecrease.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dec.png"))); // NOI18N
        menuItemDecrease.setText("Decrease");
        menuItemDecrease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDecreaseActionPerformed(evt);
            }
        });
        menuStock.add(menuItemDecrease);
        menuStock.add(jSeparator5);

        menuItemStockDetails.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        menuItemStockDetails.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuItemStockDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Details.png"))); // NOI18N
        menuItemStockDetails.setText("Stock Details");
        menuItemStockDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemStockDetailsActionPerformed(evt);
            }
        });
        menuStock.add(menuItemStockDetails);

        jMenuBar1.add(menuStock);

        menuDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete donor.png"))); // NOI18N
        menuDelete.setText("Delete Donor");
        menuDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        menuItemDeleteDonor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemDeleteDonor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuItemDeleteDonor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        menuItemDeleteDonor.setText("Delete Donor");
        menuItemDeleteDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDeleteDonorActionPerformed(evt);
            }
        });
        menuDelete.add(menuItemDeleteDonor);

        jMenuBar1.add(menuDelete);

        menuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit.png"))); // NOI18N
        menuExit.setText("Exit");
        menuExit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        menuItemLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuItemLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logout.png"))); // NOI18N
        menuItemLogout.setText("Logout");
        menuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLogoutActionPerformed(evt);
            }
        });
        menuExit.add(menuItemLogout);
        menuExit.add(jSeparator6);

        menuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuItemExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit application.png"))); // NOI18N
        menuItemExit.setText("Exit Application");
        menuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExitActionPerformed(evt);
            }
        });
        menuExit.add(menuItemExit);

        jMenuBar1.add(menuExit);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemAddDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAddDonorActionPerformed
        // TODO add your handling code here:
        new addNewDonors().setVisible(true);
        
        
    }//GEN-LAST:event_menuItemAddDonorActionPerformed

    private void menuItemDonorDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDonorDetailsActionPerformed
        // TODO add your handling code here:
        DonorDetails.displayDonorDetails();

        
        
        
  
    }//GEN-LAST:event_menuItemDonorDetailsActionPerformed

    private void menuItemLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLocationActionPerformed
        SearchDonorLocation.searchLocation();
        
    }//GEN-LAST:event_menuItemLocationActionPerformed

    private void menuItemIncreaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemIncreaseActionPerformed
        // TODO add your handling code here:
        StockIncrease.increaseStock();
        
    }//GEN-LAST:event_menuItemIncreaseActionPerformed

    private void menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(null, "Do you really want to close the application?", "Select", JOptionPane.YES_NO_OPTION);

        if (choice == JOptionPane.YES_OPTION) {
            System.exit(0);

        }




        
    }//GEN-LAST:event_menuItemExitActionPerformed

    private void menuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLogoutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new LoginView().setVisible(true);
    }//GEN-LAST:event_menuItemLogoutActionPerformed

    private void menuItemUpdateDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemUpdateDonorActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new updateDetailsDonor().setVisible(true);
    }//GEN-LAST:event_menuItemUpdateDonorActionPerformed

    private void menuItemAddDonorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_menuItemAddDonorKeyReleased
        // TODO add your handling code here:
        new addNewDonors().setVisible(true);
    }//GEN-LAST:event_menuItemAddDonorKeyReleased

    private void menuItemBloodGrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBloodGrpActionPerformed
        // TODO add your handling code here:
        SearchDonorBloodGroup.searchBloodGroup();
    }//GEN-LAST:event_menuItemBloodGrpActionPerformed

    private void menuItemDecreaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDecreaseActionPerformed
        // TODO add your handling code here:
        StockDecrease.DecreaseStock();
    }//GEN-LAST:event_menuItemDecreaseActionPerformed

    private void menuItemStockDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemStockDetailsActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        StockDetails.displayStockDetails();
    }//GEN-LAST:event_menuItemStockDetailsActionPerformed

    private void menuItemDeleteDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDeleteDonorActionPerformed
        // TODO add your handling code here:
        setVisible(false);
//        new deleteDonor().setVisible(true);
        DeleteDonor.deleteDonor();
    }//GEN-LAST:event_menuItemDeleteDonorActionPerformed

    private void menuSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSearchActionPerformed
        // TODO add your handling code here:
                SearchDonorLocation.searchLocation();

    }//GEN-LAST:event_menuSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JMenu menuDelete;
    private javax.swing.JMenu menuDonor;
    private javax.swing.JMenu menuExit;
    private javax.swing.JMenuItem menuItemAddDonor;
    private javax.swing.JMenuItem menuItemBloodGrp;
    private javax.swing.JMenuItem menuItemDecrease;
    private javax.swing.JMenuItem menuItemDeleteDonor;
    private javax.swing.JMenuItem menuItemDonorDetails;
    private javax.swing.JMenuItem menuItemExit;
    private javax.swing.JMenuItem menuItemIncrease;
    private javax.swing.JMenuItem menuItemLocation;
    private javax.swing.JMenuItem menuItemLogout;
    private javax.swing.JMenuItem menuItemStockDetails;
    private javax.swing.JMenuItem menuItemUpdateDonor;
    private javax.swing.JMenu menuSearch;
    private javax.swing.JMenu menuStock;
    // End of variables declaration//GEN-END:variables
}
